#!/usr/bin/python3
# verify_layer3_frontB.py
#
# Layer 3 Front B verifier: structural classification of the positive
# composition monoid generated by the PAB left translations L_x.
#
# This script is dependency-free. It uses exact integer Gaussian elimination
# for rank audits and writes the Front B classification tables.

from __future__ import annotations

import argparse
import csv
from collections import defaultdict, deque
from fractions import Fraction
from itertools import product
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

S = (0, 1, 2)
M = tuple((r, c) for r in S for c in S)
IDX = {x: i for i, x in enumerate(M)}

Map = Tuple[int, ...]
Phi = Tuple[int, int, int]
Triple = Tuple[Phi, Phi, Phi]


def comp(a: int, b: int) -> int:
    return (-a - b) % 3


def pab(x: Tuple[int, int], y: Tuple[int, int]) -> Tuple[int, int]:
    r1, c1 = x
    r2, c2 = y
    if r1 != r2:
        return (r1, r2)
    if c1 != c2:
        return (r1, comp(c1, c2))
    return (r1, r1)


def Lmap(x: Tuple[int, int]) -> Map:
    return tuple(IDX[pab(x, y)] for y in M)


def compose(f: Map, g: Map) -> Map:
    """Composition f after g."""
    return tuple(f[i] for i in g)


def target_row(f: Map) -> int:
    rows = {M[i][0] for i in f}
    assert len(rows) == 1
    return next(iter(rows))


def triple(f: Map) -> Triple:
    return tuple(tuple(M[f[IDX[(s, c)]]][1] for c in S) for s in S)  # type: ignore[return-value]


def map_from_triple(r: int, tr: Triple) -> Map:
    return tuple(IDX[(r, tr[s][c])] for s, c in M)


def phi_str(phi: Phi) -> str:
    return "".join(str(x) for x in phi)


def triple_str(tr: Triple) -> str:
    return "|".join(phi_str(phi) for phi in tr)


def image_size(f: Map) -> int:
    return len(set(f))


def B(r: int, a: int) -> Phi:
    """Same-row block of L_(r,a) on F_r, represented as c -> output column."""
    return tuple(r if c == a else comp(a, c) for c in S)  # type: ignore[return-value]


def phi_comp(f: Phi, g: Phi) -> Phi:
    """Composition f after g for transformations of S."""
    return tuple(f[i] for i in g)  # type: ignore[return-value]


def same_row_semigroup(r: int) -> List[Phi]:
    gens = [B(r, a) for a in S]
    sem = set(gens)
    q = deque(gens)
    while q:
        f = q.popleft()
        for g in gens:
            for h in (phi_comp(g, f), phi_comp(f, g)):
                if h not in sem:
                    sem.add(h)
                    q.append(h)
    return sorted(sem)


def expected_same_row_semigroup(r: int) -> List[Phi]:
    ident = (0, 1, 2)
    tau = tuple(r if c == r else next(u for u in S if u not in (r, c)) for c in S)
    rank2 = []
    for p in S:
        for q in S:
            if p == q:
                continue
            if p == r or q == r:
                rank2.append(tuple(p if c == r else q for c in S))
    return sorted(set([ident, tau] + rank2))


def same_row_class(r: int, U: Phi) -> str:
    if U == (0, 1, 2):
        return "identity"
    tau = tuple(r if c == r else next(u for u in S if u not in (r, c)) for c in S)
    if U == tau:
        return "tau_r"
    return "rank2_N"


def row_stay_triple(r: int, U: Phi, a: int) -> Triple:
    phi: List[Phi] = []
    for s in S:
        if s == r:
            phi.append(phi_comp(U, B(r, a)))
        else:
            phi.append((U[s], U[s], U[s]))
    return tuple(phi)  # type: ignore[return-value]


def constant_triple(t: int) -> Triple:
    return tuple((t, t, t) for _ in S)  # type: ignore[return-value]


def generate_positive_composition_semigroup():
    gens = [(x, Lmap(x)) for x in M]
    op = {v for _, v in gens}
    word = {v: f"L{x}" for x, v in gens}
    q = deque(v for _, v in gens)
    while q:
        f = q.popleft()
        for xg, g in gens:
            for h, hw in (
                (compose(g, f), f"L{xg}∘({word[f]})"),
                (compose(f, g), f"({word[f]})∘L{xg}"),
            ):
                if h not in op:
                    op.add(h)
                    word[h] = hw
                    q.append(h)
    return sorted(op, key=lambda f: (target_row(f), triple_str(triple(f)))), word


def reduced_matrix_flat(f: Map, r: int) -> List[int]:
    """Flatten 3x9 matrix Hom(k[M],F_r) in output-column rows."""
    out = [0] * (3 * 9)
    for j, y in enumerate(M):
        rr, cc = M[f[j]]
        assert rr == r
        out[cc * 9 + j] = 1
    return out


def rank_exact(rows: Iterable[Iterable[int]]) -> int:
    A = [[Fraction(x) for x in row] for row in rows]
    if not A:
        return 0
    m = len(A)
    n = len(A[0])
    rank = 0
    col = 0
    while rank < m and col < n:
        pivot = None
        for i in range(rank, m):
            if A[i][col] != 0:
                pivot = i
                break
        if pivot is None:
            col += 1
            continue
        A[rank], A[pivot] = A[pivot], A[rank]
        pv = A[rank][col]
        A[rank] = [x / pv for x in A[rank]]
        for i in range(m):
            if i != rank and A[i][col] != 0:
                fac = A[i][col]
                A[i] = [A[i][j] - fac * A[rank][j] for j in range(n)]
        rank += 1
        col += 1
    return rank


def greedy_basis(fs: List[Map], r: int) -> List[Map]:
    basis: List[Map] = []
    rows: List[List[int]] = []
    for f in sorted(fs, key=lambda u: triple_str(triple(u))):
        v = reduced_matrix_flat(f, r)
        if rank_exact(rows + [v]) > rank_exact(rows):
            basis.append(f)
            rows.append(v)
        if len(basis) == 9:
            break
    return basis


def write_csv(path: Path, rows: List[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=str(Path(__file__).resolve().parents[1]))
    args = parser.parse_args()

    root = Path(args.root)
    tables = root / "tables"
    tables.mkdir(parents=True, exist_ok=True)

    checks = []

    semigroup, words = generate_positive_composition_semigroup()
    checks.append({"check": "positive_composition_semigroup_size", "passed": len(semigroup) == 51, "value": len(semigroup)})

    same_rows = []
    duplicate_rows = []
    normal_form_rows = []
    classification_rows = []
    basis_rows = []
    span_rows = []
    product_rows = []

    by_row: Dict[int, List[Map]] = defaultdict(list)
    for f in semigroup:
        by_row[target_row(f)].append(f)

    all_normal_form_maps = set()

    for r in S:
        Br = same_row_semigroup(r)
        expected = expected_same_row_semigroup(r)
        checks.append({"check": f"B_{r}_semigroup_size", "passed": len(Br) == 6, "value": len(Br)})
        checks.append({"check": f"B_{r}_semigroup_expected_form", "passed": Br == expected, "value": ";".join(phi_str(u) for u in Br)})

        for U in Br:
            if same_row_class(r, U) == "rank2_N":
                p = U[r]
                q = next(U[s] for s in S if s != r)
            else:
                p = ""
                q = ""
            same_rows.append({
                "target_row": r,
                "U": phi_str(U),
                "class": same_row_class(r, U),
                "U(r)": p,
                "U(non_r)": q,
                "rank_on_S": len(set(U)),
            })

        # Build row-stay normal forms and duplicate audit.
        tr_to_pairs: Dict[Triple, List[Tuple[Phi, int]]] = defaultdict(list)
        for U in Br:
            for a in S:
                tr = row_stay_triple(r, U, a)
                tr_to_pairs[tr].append((U, a))
                duplicate_rows.append({
                    "target_row": r,
                    "U": phi_str(U),
                    "U_class": same_row_class(r, U),
                    "a": a,
                    "a_class": "r" if a == r else "not_r",
                    "normal_form_triple": triple_str(tr),
                })

        row_stay_triples = sorted(tr_to_pairs, key=triple_str)
        constant_triples = [constant_triple(t) for t in S]
        normal_triples = set(row_stay_triples) | set(constant_triples)
        normal_maps = {map_from_triple(r, tr) for tr in normal_triples}
        all_normal_form_maps |= normal_maps

        actual_maps = set(by_row[r])
        checks.append({"check": f"W_{r}_element_count", "passed": len(actual_maps) == 17, "value": len(actual_maps)})
        checks.append({"check": f"W_{r}_normal_form_count", "passed": len(normal_maps) == 17, "value": len(normal_maps)})
        checks.append({"check": f"W_{r}_normal_forms_match_semigroup", "passed": normal_maps == actual_maps, "value": ""})

        normal_form_rows.append({
            "target_row": r,
            "same_row_semigroup_size": len(Br),
            "raw_pairs_U_a": len(Br) * 3,
            "distinct_row_stay_forms": len(row_stay_triples),
            "global_constants": 3,
            "total_positive_monoid_elements_in_Wr": len(normal_maps),
            "count_formula": "2*3 + 4*2 + 3 = 17",
        })

        for tr in sorted(normal_triples, key=triple_str):
            f = map_from_triple(r, tr)
            pairs = tr_to_pairs.get(tr, [])
            is_const = tr in set(constant_triples)
            if is_const:
                cls = "global_constant"
                pair_label = ""
                multiplicity = ""
            else:
                cls = "row_stay"
                pair_label = ";".join(f"U={phi_str(U)},a={a}" for U, a in pairs)
                multiplicity = len(pairs)
            active_phi = phi_str(tr[r])
            off_constants = ";".join(f"F{s}->K{tr[s][0]}" for s in S if s != r)
            classification_rows.append({
                "target_row": r,
                "class": cls,
                "triple": triple_str(tr),
                "active_source_phi": active_phi,
                "off_source_constants": off_constants,
                "generating_pairs_U_a": pair_label,
                "pair_multiplicity": multiplicity,
                "image_size": image_size(f),
                "minimal_word_found": words.get(f, ""),
            })

        # Dimension and basis.
        fs = sorted(by_row[r], key=lambda f: triple_str(triple(f)))
        dim = rank_exact(reduced_matrix_flat(f, r) for f in fs)
        basis = greedy_basis(fs, r)
        checks.append({"check": f"dim_W_{r}", "passed": dim == 9, "value": dim})
        checks.append({"check": f"basis_W_{r}_size", "passed": len(basis) == 9, "value": len(basis)})
        for i, f in enumerate(basis):
            tr = triple(f)
            basis_rows.append({
                "target_row": r,
                "basis_index": i,
                "triple": triple_str(tr),
                "class": "global_constant" if tr in set(constant_triples) else "row_stay",
                "image_size": image_size(f),
                "word": words.get(f, ""),
            })
        span_rows.append({
            "target_row": r,
            "monoid_elements_in_Wr": len(fs),
            "dim_Wr": dim,
            "basis_size": len(basis),
            "row_stay_forms": len(row_stay_triples),
            "global_constants": 3,
        })

    checks.append({"check": "all_normal_forms_match_full_semigroup", "passed": all_normal_form_maps == set(semigroup), "value": len(all_normal_form_maps)})
    total_dim = sum(int(row["dim_Wr"]) for row in span_rows)
    checks.append({"check": "composition_envelope_dimension_sum", "passed": total_dim == 27, "value": total_dim})

    # Product law W_r W_s subset W_r.
    for r in S:
        Wr = by_row[r]
        for s in S:
            Ws = by_row[s]
            ok = True
            for A in Wr:
                for Bm in Ws:
                    C = compose(A, Bm)
                    if target_row(C) != r:
                        ok = False
                        break
                if not ok:
                    break
            product_rows.append({
                "left_target_row": r,
                "right_target_row": s,
                "products_checked": len(Wr) * len(Ws),
                "product_subset_left_W": ok,
            })
            checks.append({"check": f"W_{r}_times_W_{s}_subset_W_{r}", "passed": ok, "value": ""})

    write_csv(tables / "layer3_frontB_same_row_semigroup.csv", same_rows)
    write_csv(tables / "layer3_frontB_normal_form_count.csv", normal_form_rows)
    write_csv(tables / "layer3_frontB_duplicate_table.csv", duplicate_rows)
    write_csv(tables / "layer3_frontB_row_target_classification.csv", classification_rows)
    write_csv(tables / "layer3_frontB_Wr_basis.csv", basis_rows)
    write_csv(tables / "layer3_frontB_envelope_decomposition.csv", span_rows)
    write_csv(tables / "layer3_frontB_product_law.csv", product_rows)
    write_csv(tables / "layer3_frontB_verifier_checks.csv", checks)

    failed = [c for c in checks if not c["passed"]]
    if failed:
        print("Layer 3 Front B verifier: FAIL")
        for row in failed:
            print(" ", row)
        raise SystemExit(1)

    print("Layer 3 Front B verifier: PASS")
    print("  same-row block semigroup: |B_r|=6 with identity, tau_r, and four rank-2 maps")
    print("  row-target classification: 17 elements per W_r = 14 row-stay forms + 3 constants")
    print("  composition monoid: 3*17 = 51 positive elements")
    print("  envelope dimensions: dim W_r=9 for all rows, dim E=27")
    print("  product law: W_r W_s subset W_r checked structurally")


if __name__ == "__main__":
    main()
